### ISSUE TITLE
[Selenium][Python][Chrome] How to add user-data-dir to get custom profile

### ISSUE THREAD

**Issue by kanoi-suyash** [thusoy/grunt-pylint#15]
**Scenario** : I have an application which uses Chromium Embidded Framework. As a part of that, I want to check the login persistence i.e login in the app -> Close the app -> Launch the app -> Check if login persists

**Issue** : On closing the app and relaunching it, the login info doesn't persists! (This is done via selenium...)

I came to know that I have to add user-data-dir = 'C:\Users\suyasha\AppData\Local\Google\Chrome\User Data\Profile 1' so that I can persist the login info.

If I am wrong then please help me in getting the right code way.

**Sample Code** : 
---------------------------------------------
desired_cap = { 'loggingPrefs' : { 'browser' : 'ALL' },
                'chromeOptions': { 'binary'  : gfeExePath}}
.
.
.
self.gfeDriver = webdriver.Chrome(self.chrome_driver_path,desired_capabilities= desired_cap,
                    service_args=chromedriver_service_args)
---------------------------------------------

**Comment by thusoy** [comment]
Hi! I think you should post your issue to [Stack Overflow](http://stackoverflow.com/), which is a question-and-answer site for programming problems. Since your issue seems unrelated to this project (which is for automated linting of python projects), I'm closing this issue. Hope you'll be able to resolve the problem!

As for some general advice, you probably want to store the session cookie in the user data, not the login info itself. While both are sensitive data that needs to be treated carefully, cookies are more easily revoked and the backend can prompt for fresh passwords before completing sensitive actions, thus limiting the attack surface of a compromised cookie. The same is hard to do for passwords. Also passwords are likely to be re-used among sites and thus can be used to compromise other accounts the user holds, which is highly unlikely for cookies.

**Comment by kanoi-suyash** [comment]
Hey thusoy,
Greetings!
Thanks for a quick response. Your information is really fruitful.
Cheers.
